### ISSUE TITLE
Validações ao criar novo item bibliográfico

### ISSUE THREAD

**Issue by Portix-S** [Portix-S/DC-UFSCar-ES2-202301-Grupo-CGRVV-#1]
Ano -> deve ser um ano válido (de acrodo com o calendário da linguagem Java)
BibTextKey (agora Citationkey) -> deve ter no mínimo 2 caracteres, sendo o primeiro uma letra maíscula ou minúscula

Lembrar de criar novas branchs para resolver as issues

**Comment by Notargg** [comment]
Beleza, chefe!
